//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CarEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_CARTREE                     101
#define IDR_MAINFRAME                   128
#define IDR_CAREDITYPE                  129
#define IDB_CAR                         130
#define IDR_CAREDITYPE_OLD              130
#define IDB_VERTICIES                   131
#define IDB_POINT                       132
#define IDB_POLYGONS                    133
#define IDB_SCALE                       134
#define IDB_CAMERA                      135
#define IDB_HELMET                      136
#define IDB_POLYGON_DEF                 137
#define IDB_NO_DEF                      138
#define IDB_JAM                         139
#define IDB_MAX                         139
#define IDD_CAMEDIT                     140
#define IDB_TEST                        142
#define IDB_TYRE                        144
#define IDB_TYREFACE                    145
#define IDB_HELMETFACE                  147
#define IDB_HELMETTOP                   148
#define IDB_GREY                        149
#define IDB_HELMETS                     156
#define IDB_SHADOW                      157
#define IDD_JAMSELECTOR                 158
#define IDD_DIALOG2                     159
#define IDB_OFFSET                      160
#define IDB_UNK                         161
#define IDD_SELECTJAM                   162
#define IDD_TRIGGERDISTANCE             163
#define IDR_SHOWTOOLBAR                 165
#define IDD_DIALOG3                     167
#define IDB_COLORSCAN                   168
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_EDIT3                       1002
#define IDC_EDIT4                       1003
#define IDC_EDIT5                       1004
#define IDC_XSCALE                      1005
#define IDC_YSCALE                      1006
#define IDC_EDIT6                       1007
#define IDC_EDIT7                       1008
#define IDC_EDIT8                       1009
#define IDC_JAMPREVIEW                  1010
#define IDC_JAMFILE                     1011
#define IDC_DRIVER                      1012
#define IDC_JAMNAME                     1013
#define IDC_Y_SIGN                      1016
#define IDC_X_SIGN                      1017
#define IDC_COMBO3                      1019
#define IDC_COMBO4                      1020
#define IDC_DEFAULT_VAL                 1020
#define IDC_RCRONLY                     1021
#define IDC_SHAPEDEFAULT                1022
#define IDD_DATAVAL                     1300
#define IDD_VERTEXVALUE                 1301
#define IDD_DIALOG1                     1302
#define ID_GP2_EXE                      32771
#define ID_EDIT_EDITGP2LOCATION         32772
#define ID_FILEIMPORT                   32773
#define ID_FILEEXPORT                   32774
#define ID_HIGH_NOSE                    32775
#define ID_FILLOBJECTS                  32776
#define ID_SHOW_POINTS                  32779
#define ID_COPY_CAR1_TO_CAR2            32780
#define ID_SHOWTYRES                    32782
#define ID_HELMET                       32783
#define ID_CARONE                       32785
#define ID_CARTWO                       32786
#define ID_DRAWAXIS                     32787
#define ID_SHOWCAMERAS                  32789
#define ID_TEXTUREMAPS                  32790
#define ID_SHOW_SHADOW                  32792
#define ID_SHOW_LINES                   32793
#define ID_SHOW_CULLING                 32794
#define ID_SHOW_NORMALS                 32795
#define ID_SHOW_SINGLE_COLOR            32796
#define ID_LIGHTING                     32797
#define ID_SHOW_CAR                     32798
#define ID_SHOW_POINTNUMBERS            32799
#define ID_SHOW_VERTEX_NUMBERS          32800
#define ID_BUTTON32801                  32801
#define ID_SHOW_CAMERA_NUMBERS          32802
#define ID_SHOW_POLYGON_NUMBERS         32803
#define ID_JAM_SET                      32805
#define ID_CAMERA_VIEWFROMCAMERA1       32806
#define ID_CAMERA_VIEWFROMCAMERA4       32807
#define ID_CAMERA_VIEWFROMCAMERA3       32808
#define ID_CAMERA_VIEWFROMCAMERA5       32809
#define ID_CAMERA_VIEWFROMCAMERA6       32810
#define ID_CAMERA_VIEWFROMCAMERA7       32811
#define ID_CAMERA_VIEWFROMCAMERA8       32812
#define ID_CAMERA_VIEWFROMCAMERA9       32813
#define ID_NORMAL_VIEW                  32814
#define ID_CAMERA_VIEWFROMCAMERA2       32815
#define ID_CAMERA_VIEWRIGHTSIDE         32816
#define ID_CAMERA_VIEWLEFTSIDE          32817
#define ID_CAMERA_VIEWFRONT             32818
#define ID_CAMERA_VIEWBOTTOM            32819
#define ID_CAMERA_VIEWTOP               32820
#define ID_CAMERA_VIEWBACK              32821
#define ID_CAMERA_VIEWFRONTLEFT         32822
#define ID_CAMERA_VIEWFRONTRIGHT        32823
#define ID_CAMERA_VIEWBACKLEFT          32824
#define ID_CAMERA_VIEWBACKRIGHT         32825
#define ID_START_ANIMATION              32826
#define ID_ZOOM_IN                      32827
#define ID_ZOOM_OUT                     32828
#define ID_EDIT_DISTANCE_TRIGGER        32829
#define ID_JAM_VIEW                     32830
#define ID_SHOW_JAMNUMBERS              32831
#define ID_SAVE_HELMET                  32832
#define ID_FILE_IMPORTHELMET            32833
#define ID_SET_ANIMATION_DELAY          32848
#define ID_INTERNAL_JAM                 32849
#define ID_SHOW_NOSE_CONE               32850
#define ID_JAM_EXPORTRCRJAM             32851
#define ID_FILE_IMPORTGPOOBJECT         32852
#define ID_SHOW_OBJECT                  32853
#define ID_JAM_DRAWRCRJAM               32854
#define ID_JAM_PRODUCERCRIMAGES         32855

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         32856
#define _APS_NEXT_CONTROL_VALUE         1021
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
